const heroes = [
    {
        id: 'mal',
        name: 'steven strange',
        alias: 'dr. strange',
        powers: ['magic', 'smart'],
        franchise: 'marvel',
        team: ['avengers', 'defenders' ,'illuminati'],
        alignment: true,
        riavals: ['dormamu', 'nightmare', 'shuma-gorath', 'enchantress', 'baron mordo'],
        species: 'human',
        firstApp: new Date('July 1, 1963')
    },
    {
        id: 'dc1',
        name: 'kal-el',
        alias: 'superman',
        powers: ['flight', 'x-ray vision','super stright', 'leaser eyes', 'frost breath'],
        franchise: 'dc',
        team: ['justice league'],
        alignment: true,
        riavals: ['lex luthor', 'batman', 'dakrseid', 'doomday',],
        species: 'alien',
        firstApp: new Date('June 1963')
    },
    {
        id: 'im1',
        name: 'al simmons',
        alias: 'spawn',
        powers: ['immortality', 'super strength', 'regenerate' ,'necroplasm'],
        franchise: 'marvel',
        team: [null],
        alignment: true,
        riavals: ['violator', 'a devil', 'billy kinkaid'],
        species: 'hellspawn',
        firstApp: new Date('May 19, 1992')
    },
    {
        id: 'ma2',
        name: 'johnny blaze',
        alias: 'ghost rider',
        powers: ['magic', 'super strength', 'zadkiel control', 'immortality'],
        franchise: 'marvel',
        team: ['avengers'],
        alignment: true,
        riavals: ['mephisto', 'blackheart', 'orb', 'zarathos', 'manticore'],
        species: 'hellspawn',
        firstApp: new Date('August 1, 1972')
    },
    {
        id: 'ma3',
        name: 'norman osborn',
        alias: 'green goblin',
        powers: ['hoverboard', 'money', 'super smart', 'super strength'],
        franchise: 'marvel',
        team: ['sinner six'],
        alignment: true,
        riavals: ['spiderman','venom'],
        species: 'human',
        firstApp: new Date('July 1, 1963')
    },
    {
        id: 'im2',
        name: 'mark grayson',
        alias: 'invinvible',
        powers: ['super strength', 'flight', 'speed'],
        franchise: 'image',
        team: ['the pact', 'guardians of the globe' ,],
        alignment: true,
        riavals: ['thragg', 'battle beast', 'conquest', 'omin man'],
        species: 'alien',
        firstApp: new Date('August 1, 2002')
    },
    {
        id: 'dy1',
        name: 'john gillman',
        alias: 'homelander',
        powers: ['strength', 'speed', 'flight', 'laser eyes'],
        franchise: 'dynamite',
        team: ['the seven'],
        alignment: true,
        riavals: ['the boys'],
        species: 'human',
        firstApp: new Date('October 1, 2006')
    },
    {
        id: 'ma4',
        name: 'thor odinson',
        alias: 'thor',
        powers: ['mjolnir', 'lighting', 'flight'],
        franchise: 'marvel',
        team: ['avengers'],
        alignment: true,
        riavals: ['loki', 'hulk', 'enchantress', 'the god butcher', 'galactus'],
        species: 'god',
        firstApp: new Date('August 1, 1962')
    },
    {
        id: 'dc2',
        name: 'bruce wayne',
        alias: 'batman',
        powers: ['money', 'smart', 'martial arts'],
        franchise: 'dc',
        team: ['justic league', 'the bat family'],
        alignment: true,
        riavals: ['joker', 'bane', 'riddler', 'cat women'],
        species: 'human',
        firstApp: new Date('MAy 1, 1939')
    },
    {
        id: 'dc3',
        name: 'jason todd',
        alias: 'red hood',
        powers: ['martial arts', 'weapons'],
        franchise: 'dc',
        team: ['the bat family', 'the outlaws'],
        alignment: false,
        riavals: ['joker', 'batman', 'deathstroke', 'enchantress'],
        species: 'human',
        firstApp: new Date('March 1, 1983')
    },
    {
        id: 'dc4',
        name: 'racehl roth',
        alias: 'raven',
        powers: ['magic'],
        franchise: 'dc',
        team: ['teen titans'],
        alignment: true,
        riavals: ['deathstroke', 'trigon'],
        species: 'demon',
        firstApp: new Date('October 1, 1980')
    },
    {
        id: 'mil',
        name: 'oroku sake',
        alias: 'shredder',
        powers: ['martial arts', 'ninjitsu'],
        franchise: 'mirage',
        team: ['foot clan'],
        alignment: true,
        riavals: ['tmnt', 'splinter'],
        species: 'human',
        firstApp: new Date('May 1, 1984')
    },
    {
        id: 'dc5',
        name: 'hal jordan',
        alias: 'green lantern',
        powers: ['will power', 'green lantern ring'],
        franchise: 'dc',
        team: ['justice league', 'green lantern corps'],
        alignment: true,
        riavals: ['sinesteo', 'kilowog', 'orange lanterns', 'enchantress'],
        species: 'human',
        firstApp: new Date('October 1, 1959')
    },
    {
        id: 'dc6',
        name: 'megan morse',
        alias: 'miss martian',
        powers: ['shape shifting', 'telekinesis', 'intellect'],
        franchise: 'dc',
        team: ['young justic', 'teen titan'],
        alignment: true,
        riavals: ['bombshell'],
        species: 'alien',
        firstApp: new Date('August 1, 2006')
    },
    {
        id: 'dc7',
        name: 'chuck brown',
        alias: 'kite man',
        powers: ['can fly kites'],
        franchise: 'dc',
        team: null,
        alignment: false,
        riavals: ['batmn', 'catman','swamp thang'],
        species: 'human',
        firstApp: new Date('August 1, 1960')
    },
    {
        id: 'ma5',
        name: 'petter petruski',
        alias: 'past pot pete',
        powers: ['adhesive lubricant', 'smart'],
        franchise: 'marvel',
        team: ['frightful four', 'frightful five'],
        alignment: true,
        riavals: ['human torch', 'spiderman', 'captain america'],
        species: 'human',
        firstApp: new Date('January 1, 1963')
    },
    {
        id: 'ma6',
        name: 'groot',
        alias: 'groot',
        powers: ['regeneration', 'the earth'],
        franchise: 'marvel',
        team: ['guradians of the galaxy'],
        alignment: true,
        riavals: ['thanos', 'ronin', 'ego','high evolutioner'],
        species: 'alien',
        firstApp: new Date('November 1, 1960')
    },
    {
        id: 'ma7',
        name: 'victor von doom',
        alias: 'dr. doom',
        powers: ['magic', 'smart', 'money'],
        franchise: 'marvel',
        team: null,
        alignment: false,
        riavals: ['fantastic four', 'hulk', 'x-men','black panther', 'mephistio',],
        species: 'human',
        firstApp: new Date('July 1, 1962')
    },
    {
        id: 'ma8',
        name: '',
        alias: 'kange the conqueror',
        powers: ['controls technology', 'smart'],
        franchise: 'marvel',
        team: ['the counsel of kangs'],
        alignment: false,
        riavals: ['avengers', 'fantastic four'],
        species: 'human',
        firstApp: new Date('July 1, 1963')
    },
    {
        id: 'ma9',
        name: 'marc spector',
        alias: 'moon knght',
        powers: ['moon empowerment', 'detective', 'martial arts'],
        franchise: 'marvel',
        team: ['avengers'],
        alignment: true,
        riavals: ['hobgoblin', 'the boogey-man', 'bushman'],
        species: 'human',
        firstApp: new Date('August 1, 1975')
    },
    {
        id: 'dc8',
        name: 'unknown',
        alias: 'joker',
        powers: ['insanity', 'expert chemist', 'smart'],
        franchise: 'dc',
        team: ['injustice league', 'the legion of doom'],
        alignment: true,
        riavals: ['the bat family', 'justice league'],
        species: 'human',
        firstApp: new Date('April 1, 1940')
    },
    {
        id: 'ma10',
        name: 'natasha romanoff',
        alias: 'black widow',
        powers: ['guns', 'agility', 'flexibility'],
        franchise: 'marvel',
        team: ['avengers', 'shield'],
        alignment: true,
        riavals: ['task master', 'ironman', 'thanos'],
        species: 'human',
        firstApp: new Date('April 1, 1964')
    },
    {
        id: 'ma11',
        name: 'tony stark',
        alias: 'iron man',
        powers: ['money', 'smart', 'weapons'],
        franchise: 'marvel',
        team: ['avengers','illuminati'],
        alignment: true,
        riavals: ['iron monger', 'captain america', 'thanos', 'the leader'],
        species: 'human',
        firstApp: new Date('July 1, 1963')
    },
    {
        id: 'mal2',
        name: 'eddie brock',
        alias: 'venom',
        powers: ['goop', 'symbiote suit','super strength'],
        franchise: 'marvel',
        team: null,
        alignment: false,
        riavals: ['spider-man', 'carnage', 'knull', 'enchantress','shield'],
        species: 'human',
        firstApp: new Date('September 1, 1986')
    },
    {
        id: 'ma13',
        name: 'baymax',
        alias: 'baymax',
        powers: ['morph body into a dragon'],
        franchise: 'marvel',
        team: ['big hero six'],
        alignment: true,
        riavals: ['yokai'],
        species: 'robbot',
        firstApp: new Date('september 1, 1998')
    },
]
